// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHoJM_eZZ0qIn_PDi0omsxPFP5ngVtMvc',
    appId: '1:176736238242:web:014c964d6f1cb5d17975fb',
    messagingSenderId: '176736238242',
    projectId: 'asaapp-491',
    authDomain: 'asaapp-491.firebaseapp.com',
    storageBucket: 'asaapp-491.appspot.com',
    measurementId: 'G-WM0P3PT2PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSTi9eIU8CV3f338OWzfLU0nzPXi7SAY',
    appId: '1:176736238242:android:3ae732e8d876bf617975fb',
    messagingSenderId: '176736238242',
    projectId: 'asaapp-491',
    storageBucket: 'asaapp-491.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1rYA4k47nT1KnRFjUxy7qfhHzrCE48E',
    appId: '1:176736238242:ios:9eecf3180b4517b37975fb',
    messagingSenderId: '176736238242',
    projectId: 'asaapp-491',
    storageBucket: 'asaapp-491.appspot.com',
    iosClientId: '176736238242-o19emn4ha98fkcnd94icdcbge9kt3unq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter491',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1rYA4k47nT1KnRFjUxy7qfhHzrCE48E',
    appId: '1:176736238242:ios:251d2889e8ffa0297975fb',
    messagingSenderId: '176736238242',
    projectId: 'asaapp-491',
    storageBucket: 'asaapp-491.appspot.com',
    iosClientId: '176736238242-8hs1li3345eod8g6ajkskt77p0tdlemd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter491.RunnerTests',
  );
}
